### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by TWTWTWTWTWTWTWTW** [researchmm/MM-Diffusion#18]
In the requirement file, "mkl-fft==1.3.1  mkl-random==1.2.2", which requires numpy<1.23.0,>=1.22.3, yet it's also demanded that: numpy==1.23.5, which causes conflict

**Comment by TWTWTWTWTWTWTWTW** [comment]
Is it possible to renew a requirement.txt to solve these dependency problems? Thank you very much!

**Comment by URRealHero** [comment]
how did you solve it?
